version: "3.7"
services:
  mysql:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo

  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8090:8080"
    command: --verbose
    volumes:
      - ./wiremock:/home/wiremock

volumes:
  mysql-data: