version: "3.7"
services:
  mysql:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo

volumes:
  mysql-data: