spring:
   datasource:
      url: jdbc:mysql://localhost/demo
      username: root
      password: secret
   flyway:
      cleanDisabled: false

logging:
   level:
      org.hibernate.type: TRACE
      org.hibernate.SQL: DEBUG