spring:
   datasource:
      url: jdbc:mysql://localhost/demo
      username: root
      password: secret
   flyway:
      cleanDisabled: false

logging:
   level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      org.hibernate.orm.jdbc.bind: trace
      org.hibernate.orm.jdbc.extract: trace

teacherInfoServer:
   baseUrl: http://localhost:8090