spring:
   profiles:
      active: ${APP_ENVIRONMENT:local}

   jpa:
      open-in-view: false
      properties:
         hibernate:
            type:
               json_format_mapper: com.github.winter4666.bpofea.common.dao.CustomJacksonJsonFormatMapper
