apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.30
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bp-of-ea-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bp-of-ea
  template:
    metadata:
      labels:
        app: bp-of-ea
    spec:
      containers:
      - name: bp-of-ea
        image: winter4666/bp-of-ea
        env:
        - name: APP_ENVIRONMENT
          value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bp-of-ea-service
spec:
  selector:
    app: bp-of-ea
  ports:
  - port: 8080
    targetPort: 8080