name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Generate test reports
        run: mvn surefire-report:report-only surefire-report:failsafe-report-only

      - name: Archive unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: target/site/surefire-report.html

      - name: Archive integration test report
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-report
          path: target/site/failsafe-report.html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: winter4666/bp-of-ea
